FROM debian:bookworm-slim

RUN useradd -r -s /sbin/nologin nginx && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install nginx -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/list/*

EXPOSE 80

USER nginx

CMD [ "nginx", "-g", "daemon off", "-c", "/etc/nginx/nginx.conf" ]