apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}
type: Opaque
data:
{{- range $key, $value := .Values.secretData }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
{{- end }}
