apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
spec:
  selector:
    app: {{ include "application.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
