FROM ubuntu:22.04

RUN useradd -r -s /sbin/nologin nginx && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install nginx -y --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 80

USER nginx

CMD [ "nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf" ]