apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp1
  name: myapp1-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - image: shanukumarm/custom-nginx #stacksimplify/kubenginx:1.0.0
        name: myapp1-container
        ports:
          - containerPort: 80
        resources:
          requests: 
            cpu: '100m'
            memory: '128Mi'
          limits:
            cpu: '200m'
            memory: '256Mi'