apiVersion: v1
kind: LimitRange
metadata:
  name: default-cpu-mem-limit-range
  namespace: dev
spec:
  limits:
    - default:
        cpu: '500m'     # Bydefault limit 1 vCPU per container
        memory: '512Mi' # Bydefault limit 512Mi memory per container
      defaultRequest:
        cpu: '300m'     
        memory: '256Mi'
      type: Container