apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp-service
  labels: 
    app: usermgmt-webapp
spec:
  selector:
    app: usermgmt-webapp
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer