apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp1
  name: myapp1-windows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp1-windows
  template:
    metadata:
      labels:
        app: myapp1-windows
    spec:
      containers:
      - image: shanukumarm/custom-nginx #stacksimplify/kubenginx:1.0.0
        name: myapp1-container
        ports:
          - containerPort: 80
      nodeSelector:
        nodepool-type: "windows-nodepool"

