apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp1
  name: myapp1-windows
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp1-windows
  type: LoadBalancer